Fix 'destroy is not a function'
Caused by useEffect function returning non-function

https://stackoverflow.com/questions/72306420/typeerror-destroy-is-not-a-function-nextjs